spring:
  profile.active: dev
  jackson:
    default-property-inclusion: non_null
datasource:
  tomcat:
    max-active: 10
    max-idle: 10000
    max-wait: 10000
server:
  port: 8888
  tomcat:
    accessLog.enabled: true
    basedir: "${LOG_PATH}/Tomcat"
    accessLogPattern: '%h %l %u %t "%r" %s %b %D'
logging:
  path: logs
  level:
    org.springframework: info
    org.hibernate: debug

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: netnowpwd
  jpa:
    hibernate:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-test.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
