spring:
  profile.active: dev
  jackson:
    default-property-inclusion: non_null
datasource:
  tomcat:
    max-active: 10
    max-idle: 10000
    max-wait: 10000
server:
  port: 8888
  tomcat:
    accessLog.enabled: true
    basedir: "${LOG_PATH}/Tomcat"
    accessLogPattern: '%h %l %u %t "%r" %s %b %D'
logging:
  path: logs

---
spring:
  profiles: dev
datasource:
  url: jdbc:h2:mem:testdb
  data-username: sa
  data-password:
  driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: test
datasource:
  url: jdbc:h2:mem:testdb
  data-username: sa
  data-password:
  driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
